#!/usr/bin/python3
#SPDX-FileCopyrightText: 2025 Hidenori Koseki
#SPDX-License-Identifier: BSD-3-Clause

import sys

ans =0

for etc in sys.stdin:
    try:
        ans += int(etc)
    except: 
        ans += float(etc) 

# 3桁区切りで結果を出力
ans = '{:,}'.format(ans)

print(ans)
